# Generated by Django 4.2.3 on 2023-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='drfdemo_user',
        ),
    ]
