# Generated by Django 4.2.3 on 2023-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
    ]
