# Generated by Django 4.2.3 on 2023-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0002_publish_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_number',
            field=models.CharField(max_length=5, null=True, verbose_name='班级编号'),
        ),
    ]
