# Generated by Django 4.2.2 on 2023-07-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0003_remove_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drfdemo.naturalperson', verbose_name='用户'),
        ),
    ]
