# Generated by Django 4.2.3 on 2023-07-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0004_alter_student_options_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=1024, null=True, verbose_name='个性签名'),
        ),
    ]
