# Generated by Django 4.2.3 on 2023-07-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0005_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='addr',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='详细地址'),
        ),
    ]
