# Generated by Django 4.2.3 on 2023-07-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0005_alter_student_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': '出版商', 'verbose_name_plural': '出版商'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='tb_book',
        ),
        migrations.AlterModelTable(
            name='publish',
            table='tb_publish',
        ),
    ]
