# Generated by Django 4.2.3 on 2023-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0006_alter_book_options_alter_publish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_number',
            field=models.CharField(default='1', max_length=5, verbose_name='班级编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(default='1', max_length=1024, verbose_name='个性签名'),
        ),
    ]
