# Generated by Django 4.2.2 on 2023-07-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0009_alter_book_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'tb_author',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drfdemo.publish', verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, verbose_name='书籍名称'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='drfdemo.author', verbose_name='作者'),
        ),
    ]
