# Generated by Django 4.2.3 on 2023-07-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0011_alter_book_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('feature', models.CharField(choices=[('LE', '法人'), ('NA', '自然人')], default='NA', max_length=2, verbose_name='特征')),
                ('realationship', models.CharField(choices=[('PA', '合作伙伴'), ('UN', '无关')], default='PA', max_length=2, verbose_name='关系')),
                ('id_type', models.CharField(choices=[('IC', '身份证'), ('EC', '企业代码证')], max_length=2, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=32, verbose_name='证件号')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('telephone', models.CharField(max_length=16, verbose_name='电话号码')),
                ('email', models.CharField(max_length=64, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=32, verbose_name='应用系统')),
                ('account', models.CharField(max_length=16, verbose_name='帐号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfdemo.naturalperson', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='LealPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('feature', models.CharField(choices=[('LE', '法人'), ('NA', '自然人')], default='NA', max_length=2, verbose_name='特征')),
                ('realationship', models.CharField(choices=[('PA', '合作伙伴'), ('UN', '无关')], default='PA', max_length=2, verbose_name='关系')),
                ('id_type', models.CharField(choices=[('IC', '身份证'), ('EC', '企业代码证')], max_length=2, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=32, verbose_name='证件号')),
                ('short_name', models.CharField(max_length=16, verbose_name='简称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drfdemo.naturalperson', verbose_name='法人代表')),
            ],
            options={
                'verbose_name': '法人单位',
                'verbose_name_plural': '法人单位',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfdemo.lealperson', verbose_name='雇主')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drfdemo.naturalperson', verbose_name='雇员')),
            ],
            options={
                'verbose_name': '雇员',
                'verbose_name_plural': '雇员',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('leal_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfdemo.lealperson', verbose_name='法人单位')),
                ('parent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drfdemo.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
    ]
