# Generated by Django 4.2.2 on 2023-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0013_rename_lealperson_legalperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
