# Generated by Django 4.2.2 on 2023-06-21 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 8, 2, 24, 343110), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 8, 2, 24, 343110), verbose_name='建档时间'),
        ),
    ]
