# Generated by Django 4.2.2 on 2023-06-21 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 37, 297008), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 37, 297008), verbose_name='建档时间'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 37, 297008), verbose_name='建档时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=2, verbose_name='性别')),
                ('depart', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
            ],
        ),
    ]
