# Generated by Django 4.2.2 on 2023-06-21 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo_balance_alter_employee_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 40, 27694), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 40, 27694), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 11, 40, 27694), verbose_name='建档时间'),
        ),
    ]
