# Generated by Django 4.2.2 on 2023-06-21 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_create_time_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=32, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 17, 27, 53, 576169), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 17, 27, 53, 575148), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 17, 27, 53, 576169), verbose_name='建档时间'),
        ),
    ]
