# Generated by Django 4.2.2 on 2023-06-21 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_create_time_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 4, 24, 50, 234271), verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 4, 24, 50, 234271), verbose_name='建档时间'),
        ),
    ]
