# Generated by Django 4.2.2 on 2023-06-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_create_time_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='基本计量单位代码')),
                ('name', models.CharField(max_length=32, verbose_name='基本计量单位')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='客户代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='客户名称')),
                ('shot_name', models.CharField(max_length=16, unique=True, verbose_name='客户简称')),
                ('telephone_number', models.CharField(max_length=32, verbose_name='电话号码')),
                ('category', models.SmallIntegerField(choices=[(1, '客户'), (2, '供应商')], default=1, verbose_name='类别')),
                ('region', models.SmallIntegerField(choices=[(1, '华北'), (2, '东北'), (3, '华东'), (4, '华中'), (5, '华南'), (6, '西南'), (7, '西北'), (8, '港澳台')], default=1, verbose_name='区域')),
                ('status', models.SmallIntegerField(choices=[(1, '华北'), (2, '东北'), (3, '华东'), (4, '华中'), (5, '华南'), (6, '西南'), (7, '西北'), (8, '港澳台')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='生产订单号')),
                ('create_date', models.DateField(verbose_name='单据日期')),
                ('expect_date', models.DateField(verbose_name='计划完成日期')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='客户')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='生产部门')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateField(verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateField(verbose_name='建档时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='建档时间'),
        ),
        migrations.CreateModel(
            name='UomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_group_code', models.CharField(max_length=32, unique=True, verbose_name='计量单位组代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='计量单位组')),
                ('level', models.SmallIntegerField(choices=[(1, '主计量'), (2, '辅助计量')], default=1, verbose_name='计量类别')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='换算率')),
                ('basic_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basicuom', verbose_name='计量单位')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='生产订单行号')),
                ('expect_date', models.DateField(verbose_name='计划完成日期')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量')),
                ('production_order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productionorder', verbose_name='生产订单号')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='物料编码')),
                ('code', models.CharField(max_length=32, verbose_name='物料代码')),
                ('name', models.CharField(max_length=32, verbose_name='物料名称')),
                ('uom', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.uomgroup', verbose_name='计量单位')),
            ],
        ),
    ]
