# Generated by Django 4.2.2 on 2023-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_basicuom_partner_productionorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='shot_name',
            new_name='short_name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '启用'), (2, '停用')], default=1, verbose_name='状态'),
        ),
    ]
