# Generated by Django 4.2.2 on 2023-06-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_task_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='工单号')),
                ('create_date', models.DateField(verbose_name='单据日期')),
                ('planned_start_date', models.DateField(verbose_name='计划开始日期')),
                ('planned_completion_date', models.DateField(verbose_name='计划完工日期')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('status', models.SmallIntegerField(choices=[(1, '开立'), (2, '开启'), (3, '执行'), (4, '停滞'), (5, '完工'), (6, '关闭')], default=1, verbose_name='状态')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='产品')),
                ('create_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='操作员')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='客户')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='生产部门')),
            ],
        ),
    ]
