# Generated by Django 4.2.2 on 2023-06-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_workorder_create_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.material', verbose_name='产品'),
        ),
    ]
