# Generated by Django 4.2.2 on 2023-06-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_product_workorder_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='create_name',
            new_name='admin',
        ),
    ]
