# Generated by Django 4.2.2 on 2023-06-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_create_name_workorder_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='customer',
            new_name='partner',
        ),
    ]
