# Generated by Django 4.2.2 on 2023-06-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_customer_workorder_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.CharField(default=None, max_length=128, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='建档时间'),
        ),
    ]
