# Generated by Django 4.2.2 on 2023-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_employee_photo_alter_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.FileField(default=None, max_length=128, upload_to='employee/', verbose_name='图片'),
        ),
    ]
