# Generated by Django 4.2.2 on 2023-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '开立'), (2, '开启'), (3, '执行'), (4, '停滞'), (5, '完工'), (6, '关闭'), (7, '撤销')], default=1, verbose_name='状态'),
        ),
    ]
