# Generated by Django 4.2.3 on 2023-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_team_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=16, verbose_name='班组代码'),
        ),
    ]
