# Generated by Django 4.2.3 on 2023-07-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_team_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='erp_team',
        ),
    ]
