# Generated by Django 4.2.3 on 2023-07-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='出版商')),
                ('email', models.EmailField(max_length=254, verbose_name='出版商邮箱')),
            ],
            options={
                'verbose_name': '出版商',
                'verbose_name_plural': '出版商',
                'db_table': 'app01_publish',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.BooleanField(default=1, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('class_number', models.CharField(default='1', max_length=5, verbose_name='班级编号')),
                ('description', models.TextField(default='1', max_length=1024, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'app01_student',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('pub_date', models.DateField(verbose_name='出版日期')),
                ('bread', models.IntegerField(verbose_name='阅读量')),
                ('bcomment', models.IntegerField(verbose_name='评论量')),
                ('publish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.publish')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'app01_book',
            },
        ),
    ]
